### ISSUE TITLE
Invalid SSL certificate Error code `526`

### ISSUE THREAD

**Issue by nelsonic** [psantos10/psantos10#1]
Hi @psantos10 👋 
Just wanted to say a quick thank you for your intro to deploying `Phoenix` with `Kamal` ❤️ 
https://blog.psantos.dev/deploying-phoenix-application-with-kamal-2/

And inform you that we tried to view your personal site and got a `526` error:
https://psantos.dev/
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/ce315887-e1ab-493c-9050-7fdf7e592b5c">

Tried in several browsers. All same error. 😞 

Bad cert: https://community.cloudflare.com/t/invalid-ssl-certificate-error-code-526/471136 🔒 
Are you hosting your personal site using `Kamala`? 💭 

Thanks again. 👌

**Comment by psantos10** [comment]
Hi @nelsonic 

thank you for the heads up. 

At the moment the main website is unavailable. I will add a redirect to the homepage.

**Comment by nelsonic** [comment]
Cool. Happy to close as you have it under control. ✅
